services:
  angie:
    image: docker.angie.software/angie:1.9.1
    container_name: angie
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./angie.conf:/etc/angie/angie.conf
      - ./options-ssl-angie.conf:/etc/angie/options-ssl-angie.conf
      - 3x-ui-aio-volume:/var/lib/angie/acme/
    networks:
      - 3x-ui-aio-network
    restart: unless-stopped

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    volumes:
      - 3x-ui-aio-volume:/etc/x-ui/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "false"
    tty: true
    networks:
      - 3x-ui-aio-network
    restart: unless-stopped

  authorization-stub:
    image: ampetelin/authorization-stub:latest
    container_name: authorization-stub
    networks:
      - 3x-ui-aio-network
    restart: unless-stopped

networks:
  3x-ui-aio-network:
    name: 3x-ui-aio-network

volumes:
  3x-ui-aio-volume:
    name: 3x-ui-aio-volume
